# Generated by Django 4.2.20 on 2025-04-07 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Telefon Numarası"),
                ),
                (
                    "student_full_name",
                    models.CharField(max_length=255, verbose_name="Öğrenci Adı Soyadı"),
                ),
                (
                    "school_name",
                    models.CharField(max_length=255, verbose_name="Okul Adı"),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="Onay Durumu"),
                ),
                (
                    "notification_preferences",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Bildirim Tercihleri"
                    ),
                ),
            ],
            options={
                "verbose_name": "Kullanıcı Profili",
                "verbose_name_plural": "Kullanıcı Profilleri",
            },
        ),
    ]
