# Generated by Django 4.2.20 on 2025-04-07 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
        ("forum", "0005_attachment"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopicFollow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "followed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Takip Başlama Zamanı"
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to="forum.topic",
                        verbose_name="Takip Edilen Konu",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followed_topics",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Takip Eden Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Konu Takibi",
                "verbose_name_plural": "Konu Takipleri",
                "ordering": ["-followed_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportedContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content_object_id", models.PositiveIntegerField()),
                (
                    "reason",
                    models.TextField(blank=True, verbose_name="Raporlama Sebebi"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("yeni", "Yeni"),
                            ("incelendi", "İncelendi"),
                            ("reddedildi", "Reddedildi"),
                        ],
                        db_index=True,
                        default="yeni",
                        max_length=10,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "reported_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Raporlama Zamanı"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Çözülme Zamanı"
                    ),
                ),
                (
                    "content_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Raporlayan",
                    ),
                ),
                (
                    "resolver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Çözen Yönetici",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rapor Edilen İçerik",
                "verbose_name_plural": "Rapor Edilen İçerikler",
                "ordering": ["-reported_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verb", models.CharField(max_length=255, verbose_name="Eylem")),
                (
                    "target_object_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "action_object_object_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Okundu Mu?"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Oluşturulma Tarihi",
                    ),
                ),
                (
                    "action_object_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_action",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acted_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Etken",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Alıcı",
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_target",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bildirim",
                "verbose_name_plural": "Bildirimler",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="topicfollow",
            constraint=models.UniqueConstraint(
                fields=("user", "topic"), name="unique_user_topic_follow"
            ),
        ),
    ]
